### PR TITLE
Add Observable to Tools

### PR DESCRIPTION
**Pull request by thSoft**

### CODE REVIEW

**Comment by ncase** [comment]
That's a great suggestion!  Thanks for the pull request :)

**Comment by thSoft** [comment]
Uh oh, now the home page doesn't list anything but displays "loading..." forever. Did I break something? 🤔

**Comment by ncase** [comment]
Eep!  Yeah the PR broke it, but it's less your fault and more "my code somehow is so fragile it can't handle a .csv file with a newline at the end of it."  Trying to fix it now!

**Comment by thSoft** [comment]
Aw, snap! Sorry, and thanks for merging anyway!

**Comment by ncase** [comment]
Bug fixed! (+ added a bunch of other explorables)

No worries!  This is a good reminder I need to get into the habit of _actually_ testing new PRs locally first :P

**Pull request merged**
